### ISSUE TITLE
SkyBoxes: Filenames not correct in 2da

### ISSUE THREAD

**Issue by plenarius** [pstemarie/Neverwinter_Dark_Ages#10]
The skyboxes in the 2da are named `sky_q_*` but the files themselves do not contain the `q`

**Comment by pstemarie** [comment]
Fixed. 

The 2da was using an older set of filenames. Not sure where the mdl duplication came from, but there were two sets of models in the old Project Q source I have. The mdl files without "_q_" in the name were the newest, so I went with those.
