### ISSUE TITLE
appearance.2da: Row numbers go from 15099 to 16000, could cause later conflicts

### ISSUE THREAD

**Issue by plenarius** [pstemarie/Neverwinter_Dark_Ages#11]
Looks like you accidentally missed 900 rows of padding :)

**Comment by pstemarie** [comment]
I actually forgot to use the "resequence numbers" numbers on the tool I use for editing 2da files. They're renumbered now and I've changed the wiki to reflect the new reserved range in appearance.2da - which is now rows 15100-16100.
