### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Mechaslav** [pstemarie/Neverwinter_Dark_Ages#37]
It says that it was made for ean updated version of NWN. Do I need to somehow update the toolset? If so how do I do that? I was under the impression it would be staying at 1.69.

**Comment by pstemarie** [comment]
This project is for the Enhanced Edition by Beamdog. It is not compatible with v1.69. You would need to purchase the EE (via Steam) and update the game to Preview v8193.22.

The Preview patch is available only through Steam and is accessed from the Betas Tab of the Game Properties by entering the code "previewpreview" in the box and hitting "Check Code".
