### ISSUE TITLE
TNO01 Crashy Tile tno01_v08_01 (and a couple other buggy ones)

### ISSUE THREAD

**Issue by plenarius** [pstemarie/Neverwinter_Dark_Ages#42]
Our users were crashing in an area and it turned out to be the tile `tno01_v08_01`. I ran all your TNO01 through Clean Models (though it looks like you did that already) and the following are buggy and failed to export:

- `tno01_v07_04`
- `tno01_v08_01`
- `tno01_v69_02`

`tno01_v07_04` and `tno01_v69_02` seem really bad, even if I run the compiled base game models from the bif through cm3, cm3 dies. Not sure if you have the ASCII versions of those?

I'm also curious why this area worked fine before 8193.20 - anyway not sure if there's much you can do here but for reporting sake. Feel free to close if nothing you can do.

P.S. sorry if TL;DR

**Comment by pstemarie** [comment]
Those tiles are actually from the ascii source package I got from Beamdog and I haven't done anything to them - along with the other sea cliff tiles - other than drop the ascii files into a hak. I'd make a report to DEV and maybe Bill can take a look. With those tiles, being animesh, I'm loathe to do anything on my own as I have bad luck with such things.
