### ISSUE TITLE
qp_bark_*.dds missing from package

### ISSUE THREAD

**Issue by plenarius** [pstemarie/Neverwinter_Dark_Ages#43]
A few tno01_a* files reference bitmap `qp_bark_04` and `qp_bark_06` - those textures don't exist in your package

Also I noticed `isc02_f01_09.mdl` uses `qp_crate`

**Comment by pstemarie** [comment]
Thanks, they'll be in the next update

**Comment by pstemarie** [comment]
Added missing textures and fancy maps
